/**
* @author Vishnu Belkone
* @date 10/08/2015
* @description - this class is an wrapper class of contact fields which we have to use in post/put service. 
*/
public class ContactServiceBodywrapper {
    public Integer Id;  //0
    public Integer CustomerId;  //1520666
    public String Title;    //Mr
    public String FirstName;    //Scott
    public String LastName; //Teacher
    public String Name; //Scott Teacher
    public String Phone;    //0299694566
    public String Fax;  //0299694566
    public String Email;    //scott@test.com
    public String Mobile;   //0404555666
    public boolean IsMainSalesContact;
    public boolean IsMainAccountContact;
    public String IsActive;
    public String Description;  //Cool Teacher
    //public cls_MainContactFor[] MainContactFor;
    public String JobTitle; //Teacher
    public String ExternalId;   //003N000000SBDyk
    public boolean IsMathleticsContact;
    public boolean IsSpellodromeContact;
    public boolean IsReadingEggsContact;
    public boolean IsIntoScienceContact;
    class cls_MainContactFor {
    }   
}